
name: "Uron CI Tests"

on: push

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r tests/requirements.txt
        
    - name: Lint
      run: |
        pip install pre-commit
        pre-commit install
        pre-commit run --all-files

    - name: Test with pytest
      run: |
        python -m pytest --cov=uron -s tests
